name: Main workflow

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: "0 0 * * 5"

jobs:
  plugin_test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v4
        with:
          command: lean --version

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y bats zstd

      - name: Install asdf
        uses: asdf-vm/actions/setup-asdf@v2

      - name: Test plugin
        run: |
          asdf plugin add lean "$GITHUB_WORKSPACE"
          bats test

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run ShellCheck
        run: shellcheck bin/* lib/*

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install shfmt
        run: |
          sudo apt-get update -q
          sudo apt-get install -y shfmt

      - name: Run shfmt
        run: shfmt -d -i 2 -ci .
